Seminar 1/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Seminar_1.Models.VMs;

namespace Seminar_1.Controllers
{
    public class LoginController : Controller
    {
        private readonly Seminar1Context context;

        public LoginController( Seminar1Context context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new LoginVM());
      
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginVM loginVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                return View(loginVM);
            }

            // var user = Models.Entities.User.GetAll().FirstOrDefault(u => u.UserName == loginVM.UserName);

                     
            var user = context.Users.FirstOrDefault(u => u.UserName ==loginVM.UserName);                
                
                    

            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Invalid Credentials");
                return View(loginVM);
            }

            if (user.Password != Base64.Base64Encode(loginVM.Password))
            {
                ModelState.AddModelError(string.Empty, "Invalid Credentials");
                return View(loginVM);
            }

            List<Claim> claims = new List<Claim>()
            {
                new Claim(ClaimTypes.NameIdentifier, loginVM.UserName),
            };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            AuthenticationProperties properties = new AuthenticationProperties()
            {
                AllowRefresh = true,
                IsPersistent = false,
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

    
}
}

Seminar 1/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
using Microsoft.Extensions.Hosting.Internal;
using Seminar_1.Models.Entities;
using Seminar_1.Models.VMs;

namespace Seminar_1.Controllers
{
    [Route("[Controller]")]
    public class ProductController : Controller
    {
        private const string imgFolderName = "img";
        private readonly IWebHostEnvironment hostEnvironment;
        private readonly Seminar1Context context;

        public ProductController(IWebHostEnvironment hostEnvironment, Seminar1Context context)
        {      
            this.hostEnvironment= hostEnvironment;
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var list = context.Products.Select(p => new ProductVM().ProdToProdVM(p)).ToList();
            return View(list);
        }

        [HttpGet]
        [Route("New")]
        public IActionResult New()
        {
            var product = new ProductVM();
            return View(product);
        }

        [HttpPost]
        [Route("New")]
        public IActionResult Create(ProductVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");           
                return View("New", dto);
            }

            SaveImage(dto);
            context.Add(ProductVM.VMProdToProd(dto));
            context.SaveChanges();

            return View("Index", context.Products.Select(p => new ProductVM().ProdToProdVM(p)).ToList());
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var prod = context.Products.FirstOrDefault(p => p.Id == id);

            if (prod == null)
                return View("Index", context.Products.Select(p => new ProductVM().ProdToProdVM(p)).ToList());
            else
                return View(new ProductVM().ProdToProdVM(prod));
        }

        [HttpPost]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id, ProductVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");               
                return View($"Edit/{id}", dto);
            }

            var prod = context.Products.FirstOrDefault(p => p.Id == id);
            if (prod == null)
                return View("Index", context.Products.Select(p => new ProductVM().ProdToProdVM(p)).ToList());

            var oldFileRelativePath = prod.ImagePath;
            if (dto.ProducImage == null)
                dto.ImagePath = oldFileRelativePath;
            else
            {
                if (!string.IsNullOrWhiteSpace(oldFileRelativePath))
                {
                    var olfFileFullPath = Path.Combine(hostEnvironment.WebRootPath, oldFileRelativePath);
                    if (System.IO.File.Exists(olfFileFullPath))
                        System.IO.File.Delete(olfFileFullPath);
                }

                SaveImage(dto);
            }

            prod.Name = dto.Name;
            prod.Description = dto.Description;
            prod.Price = dto.Price;
            prod.IsAvailable = dto.IsAvailable;
            prod.ImagePath = dto.ImagePath;

            context.Products.Update(prod);
            context.SaveChanges();


            return View("Index", context.Products.Select(p => new ProductVM().ProdToProdVM(p)).ToList());
        }

        [HttpDelete]
        [Route("Delete/{id}")]
        public JsonResult Delete(int id)
        {
            var prod = context.Products.FirstOrDefault(p => p.Id == id);
            if (prod == null)
                return Json(new { success = true, message = "Already Deleted" });

            if (!string.IsNullOrWhiteSpace(prod.ImagePath))
            {
                var filePath = Path.Combine(hostEnvironment.WebRootPath, prod.ImagePath);

                if (System.IO.File.Exists(filePath))
                    System.IO.File.Delete(filePath);
            }

            context.Products.Remove(prod);
            context.SaveChanges();

            return Json(new { success = true, message = "Delete success" });
        }

        private void SaveImage(ProductVM dto)
        {
            if (dto.ProducImage == null)
                return;

            var imgFolderPath = Path.Combine(hostEnvironment.WebRootPath, imgFolderName);

            if (!Directory.Exists(imgFolderPath))
                Directory.CreateDirectory(imgFolderPath);

            var fileName = Guid.NewGuid() + Path.GetExtension(dto.ProducImage.FileName);
            var imgFullPath = Path.Combine(imgFolderPath, fileName);

            using (var fileStream = new FileStream(imgFullPath, FileMode.Create))
                dto.ProducImage.CopyTo(fileStream);

            dto.ImagePath = Path.Combine(imgFolderName, fileName);
        }         
    }
}

Seminar 1/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Seminar_1.Models.VMs;

namespace Seminar_1.Controllers
{
    [Route("[Controller]")]
    [Authorize]
    public class UserController : Controller
    {
        private readonly Seminar1Context context;

        public UserController(Seminar1Context context)
        {
            this.context = context;
        }

        
        [HttpGet]
        public IActionResult Index()
        {
            var list = context.Users.Select(p => new UserVM().UserToUserVM(p)).ToList();
            return View(list);
        }

        [HttpGet]
        [Route("New")]
        public IActionResult New()
        {
            var user = new UserVM();
            return View(user);
        }

        [HttpPost]
        [Route("New")]
        public IActionResult Create(UserVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                return View("New", dto);
            }

            if (dto.Password != dto.ConfirmPassword)
            {
                ModelState.AddModelError(string.Empty, "Password and ConfirmPassword doesn't match");
                return View("New", dto);
            }

            dto.Password=Base64.Base64Encode(dto.ConfirmPassword);
            
            context.Users.Add(UserVM.VMUserToUser(dto));
            context.SaveChanges();

            return View("Index", context.Users.Select(p => new UserVM().UserToUserVM(p)).ToList());
        }

        [HttpDelete]
        [Route("Delete/{id}")]
        public JsonResult Delete(int id)
        {
            var user = context.Users.FirstOrDefault(p => p.Id == id);
            if (user == null)
                return Json(new { success = true, message = "Already Deleted" });

         

            context.Users.Remove(user);
            context.SaveChanges();

            return Json(new { success = true, message = "Delete success" });
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var user = context.Users.FirstOrDefault(p => p.Id == id);

            if (user == null)
                return View("Index", context.Users.Select(p => new UserVM().UserToUserVM(p)).ToList());
            else
                return View(new UserVM().UserToUserVM(user));
        }

        [HttpPost]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id, UserVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "There were some errors in your form");
                return View($"Edit/{id}", dto);
            }

            var user = context.Users.FirstOrDefault(p => p.Id == id);
            if (user == null)
                return View("Index", context.Users.Select(p => new UserVM().UserToUserVM(p)).ToList());

            
            user.UserName = dto.UserName;
            user.SurName = dto.SurName;
            user.Name = dto.Name;
            

            context.Users.Update(user);
            context.SaveChanges();


            return View("Index", context.Users.Select(p => new UserVM().UserToUserVM(p)).ToList());
        }

    }
}

Seminar 1/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor

@{
    var shoppingList = HttpContextAccessor.HttpContext.Session.Get<List<int>>(SessionHelper.ShoppingCart);
    var shoppingCount = shoppingList == null ? 0 : shoppingList.Count;

    bool isUserAuth = (HttpContextAccessor.HttpContext.User != null) && (HttpContextAccessor.HttpContext.User.Identity != null) && HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Antique.Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Antique Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                      


                        @if (!isUserAuth)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" sp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" sp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" sp-area="" asp-controller="User" asp-action="Index">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark"><span class="fas fa-shopping-cart"></span> &nbsp; (@shoppingCount)</a>
                        </li> 
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Footer section
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fontawesome/js/all.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/product.js"></script>
    <script src="~/js/user.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>